# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Parameters.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog_Parametrs(object):
    def setupUi(self, Dialog_Parametrs):
        Dialog_Parametrs.setObjectName(_fromUtf8("Dialog_Parametrs"))
        Dialog_Parametrs.resize(501, 610)
        self.gridLayout = QtGui.QGridLayout(Dialog_Parametrs)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(Dialog_Parametrs)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 464, 1360))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.formLayout_9 = QtGui.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout_9.setObjectName(_fromUtf8("formLayout_9"))
        self.frameParameter_1 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frameParameter_1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameParameter_1.setFrameShadow(QtGui.QFrame.Raised)
        self.frameParameter_1.setObjectName(_fromUtf8("frameParameter_1"))
        self.formLayout = QtGui.QFormLayout(self.frameParameter_1)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.frameParameter_1)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtGui.QLineEdit(self.frameParameter_1)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtGui.QLabel(self.frameParameter_1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtGui.QLineEdit(self.frameParameter_1)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_3 = QtGui.QLabel(self.frameParameter_1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_3 = QtGui.QLineEdit(self.frameParameter_1)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_4 = QtGui.QLabel(self.frameParameter_1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_4 = QtGui.QLineEdit(self.frameParameter_1)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_6 = QtGui.QLabel(self.frameParameter_1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.comboBox = QtGui.QComboBox(self.frameParameter_1)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.comboBox)
        self.label_48 = QtGui.QLabel(self.frameParameter_1)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label_48)
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.SpanningRole, self.frameParameter_1)
        self.frameParameter_2 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frameParameter_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameParameter_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frameParameter_2.setObjectName(_fromUtf8("frameParameter_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.frameParameter_2)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_41 = QtGui.QLabel(self.frameParameter_2)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label_41)
        self.label_5 = QtGui.QLabel(self.frameParameter_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_5 = QtGui.QLineEdit(self.frameParameter_2)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_5)
        self.label_7 = QtGui.QLabel(self.frameParameter_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_6 = QtGui.QLineEdit(self.frameParameter_2)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_6)
        self.label_8 = QtGui.QLabel(self.frameParameter_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_7 = QtGui.QLineEdit(self.frameParameter_2)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_7)
        self.label_9 = QtGui.QLabel(self.frameParameter_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_8 = QtGui.QLineEdit(self.frameParameter_2)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_8)
        self.label_10 = QtGui.QLabel(self.frameParameter_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_10)
        self.comboBox_2 = QtGui.QComboBox(self.frameParameter_2)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.comboBox_2)
        self.formLayout_9.setWidget(1, QtGui.QFormLayout.SpanningRole, self.frameParameter_2)
        self.frameParameter_3 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frameParameter_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameParameter_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frameParameter_3.setObjectName(_fromUtf8("frameParameter_3"))
        self.formLayout_5 = QtGui.QFormLayout(self.frameParameter_3)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_21 = QtGui.QLabel(self.frameParameter_3)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_21)
        self.lineEdit_17 = QtGui.QLineEdit(self.frameParameter_3)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_17)
        self.label_22 = QtGui.QLabel(self.frameParameter_3)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_22)
        self.lineEdit_18 = QtGui.QLineEdit(self.frameParameter_3)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_18)
        self.label_23 = QtGui.QLabel(self.frameParameter_3)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_23)
        self.lineEdit_19 = QtGui.QLineEdit(self.frameParameter_3)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_19)
        self.label_24 = QtGui.QLabel(self.frameParameter_3)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_24)
        self.lineEdit_20 = QtGui.QLineEdit(self.frameParameter_3)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit_20)
        self.label_25 = QtGui.QLabel(self.frameParameter_3)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.formLayout_5.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_25)
        self.comboBox_5 = QtGui.QComboBox(self.frameParameter_3)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.formLayout_5.setWidget(6, QtGui.QFormLayout.FieldRole, self.comboBox_5)
        self.label_42 = QtGui.QLabel(self.frameParameter_3)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label_42)
        self.formLayout_9.setWidget(2, QtGui.QFormLayout.SpanningRole, self.frameParameter_3)
        self.frameParameter_4 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frameParameter_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameParameter_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frameParameter_4.setObjectName(_fromUtf8("frameParameter_4"))
        self.formLayout_6 = QtGui.QFormLayout(self.frameParameter_4)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_26 = QtGui.QLabel(self.frameParameter_4)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_26)
        self.lineEdit_21 = QtGui.QLineEdit(self.frameParameter_4)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_21)
        self.label_27 = QtGui.QLabel(self.frameParameter_4)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_27)
        self.lineEdit_22 = QtGui.QLineEdit(self.frameParameter_4)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_22)
        self.label_28 = QtGui.QLabel(self.frameParameter_4)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_28)
        self.lineEdit_23 = QtGui.QLineEdit(self.frameParameter_4)
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_23)
        self.label_29 = QtGui.QLabel(self.frameParameter_4)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.formLayout_6.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_29)
        self.lineEdit_24 = QtGui.QLineEdit(self.frameParameter_4)
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.formLayout_6.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_24)
        self.label_30 = QtGui.QLabel(self.frameParameter_4)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.formLayout_6.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_30)
        self.comboBox_6 = QtGui.QComboBox(self.frameParameter_4)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.formLayout_6.setWidget(5, QtGui.QFormLayout.FieldRole, self.comboBox_6)
        self.label_43 = QtGui.QLabel(self.frameParameter_4)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label_43)
        self.formLayout_9.setWidget(3, QtGui.QFormLayout.SpanningRole, self.frameParameter_4)
        self.frameParameter_5 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frameParameter_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameParameter_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frameParameter_5.setObjectName(_fromUtf8("frameParameter_5"))
        self.formLayout_7 = QtGui.QFormLayout(self.frameParameter_5)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.label_31 = QtGui.QLabel(self.frameParameter_5)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_31)
        self.lineEdit_25 = QtGui.QLineEdit(self.frameParameter_5)
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_25)
        self.label_32 = QtGui.QLabel(self.frameParameter_5)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_32)
        self.lineEdit_26 = QtGui.QLineEdit(self.frameParameter_5)
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_26)
        self.label_33 = QtGui.QLabel(self.frameParameter_5)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_33)
        self.lineEdit_27 = QtGui.QLineEdit(self.frameParameter_5)
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_27)
        self.label_34 = QtGui.QLabel(self.frameParameter_5)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_34)
        self.lineEdit_28 = QtGui.QLineEdit(self.frameParameter_5)
        self.lineEdit_28.setObjectName(_fromUtf8("lineEdit_28"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_28)
        self.label_35 = QtGui.QLabel(self.frameParameter_5)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_35)
        self.comboBox_7 = QtGui.QComboBox(self.frameParameter_5)
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.FieldRole, self.comboBox_7)
        self.label_44 = QtGui.QLabel(self.frameParameter_5)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label_44)
        self.formLayout_9.setWidget(4, QtGui.QFormLayout.SpanningRole, self.frameParameter_5)
        self.framePraameter_6 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.framePraameter_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.framePraameter_6.setFrameShadow(QtGui.QFrame.Raised)
        self.framePraameter_6.setObjectName(_fromUtf8("framePraameter_6"))
        self.formLayout_3 = QtGui.QFormLayout(self.framePraameter_6)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_11 = QtGui.QLabel(self.framePraameter_6)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_11)
        self.lineEdit_9 = QtGui.QLineEdit(self.framePraameter_6)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_9)
        self.label_12 = QtGui.QLabel(self.framePraameter_6)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_12)
        self.lineEdit_10 = QtGui.QLineEdit(self.framePraameter_6)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_10)
        self.label_13 = QtGui.QLabel(self.framePraameter_6)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_13)
        self.lineEdit_11 = QtGui.QLineEdit(self.framePraameter_6)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_11)
        self.label_14 = QtGui.QLabel(self.framePraameter_6)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_12 = QtGui.QLineEdit(self.framePraameter_6)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_12)
        self.label_15 = QtGui.QLabel(self.framePraameter_6)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_15)
        self.comboBox_3 = QtGui.QComboBox(self.framePraameter_6)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.comboBox_3)
        self.label_45 = QtGui.QLabel(self.framePraameter_6)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label_45)
        self.formLayout_9.setWidget(5, QtGui.QFormLayout.SpanningRole, self.framePraameter_6)
        self.frameParameter_7 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frameParameter_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameParameter_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frameParameter_7.setObjectName(_fromUtf8("frameParameter_7"))
        self.formLayout_4 = QtGui.QFormLayout(self.frameParameter_7)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_16 = QtGui.QLabel(self.frameParameter_7)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_16)
        self.lineEdit_13 = QtGui.QLineEdit(self.frameParameter_7)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_13)
        self.label_17 = QtGui.QLabel(self.frameParameter_7)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_17)
        self.lineEdit_14 = QtGui.QLineEdit(self.frameParameter_7)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_14)
        self.label_18 = QtGui.QLabel(self.frameParameter_7)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_18)
        self.lineEdit_15 = QtGui.QLineEdit(self.frameParameter_7)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_15)
        self.label_19 = QtGui.QLabel(self.frameParameter_7)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_19)
        self.lineEdit_16 = QtGui.QLineEdit(self.frameParameter_7)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_16)
        self.label_20 = QtGui.QLabel(self.frameParameter_7)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_20)
        self.comboBox_4 = QtGui.QComboBox(self.frameParameter_7)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.FieldRole, self.comboBox_4)
        self.label_46 = QtGui.QLabel(self.frameParameter_7)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label_46)
        self.formLayout_9.setWidget(6, QtGui.QFormLayout.SpanningRole, self.frameParameter_7)
        self.frameParameter_8 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frameParameter_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameParameter_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frameParameter_8.setObjectName(_fromUtf8("frameParameter_8"))
        self.formLayout_8 = QtGui.QFormLayout(self.frameParameter_8)
        self.formLayout_8.setObjectName(_fromUtf8("formLayout_8"))
        self.label_47 = QtGui.QLabel(self.frameParameter_8)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.SpanningRole, self.label_47)
        self.label_36 = QtGui.QLabel(self.frameParameter_8)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_36)
        self.lineEdit_29 = QtGui.QLineEdit(self.frameParameter_8)
        self.lineEdit_29.setObjectName(_fromUtf8("lineEdit_29"))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_29)
        self.label_37 = QtGui.QLabel(self.frameParameter_8)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.formLayout_8.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_37)
        self.lineEdit_30 = QtGui.QLineEdit(self.frameParameter_8)
        self.lineEdit_30.setObjectName(_fromUtf8("lineEdit_30"))
        self.formLayout_8.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_30)
        self.label_38 = QtGui.QLabel(self.frameParameter_8)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.formLayout_8.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_38)
        self.lineEdit_31 = QtGui.QLineEdit(self.frameParameter_8)
        self.lineEdit_31.setObjectName(_fromUtf8("lineEdit_31"))
        self.formLayout_8.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_31)
        self.label_39 = QtGui.QLabel(self.frameParameter_8)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.formLayout_8.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_39)
        self.lineEdit_32 = QtGui.QLineEdit(self.frameParameter_8)
        self.lineEdit_32.setObjectName(_fromUtf8("lineEdit_32"))
        self.formLayout_8.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit_32)
        self.label_40 = QtGui.QLabel(self.frameParameter_8)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.formLayout_8.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_40)
        self.comboBox_8 = QtGui.QComboBox(self.frameParameter_8)
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.formLayout_8.setWidget(6, QtGui.QFormLayout.FieldRole, self.comboBox_8)
        self.formLayout_9.setWidget(7, QtGui.QFormLayout.FieldRole, self.frameParameter_8)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog_Parametrs)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog_Parametrs)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog_Parametrs.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog_Parametrs.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Parametrs)

    def retranslateUi(self, Dialog_Parametrs):
        Dialog_Parametrs.setWindowTitle(_translate("Dialog_Parametrs", "Dialog", None))
        self.label.setText(_translate("Dialog_Parametrs", "Element Name", None))
        self.label_2.setText(_translate("Dialog_Parametrs", "Units", None))
        self.label_3.setText(_translate("Dialog_Parametrs", "Min. Value", None))
        self.label_4.setText(_translate("Dialog_Parametrs", "Max Value", None))
        self.label_6.setText(_translate("Dialog_Parametrs", "No. of Characters", None))
        self.comboBox.setItemText(0, _translate("Dialog_Parametrs", "1", None))
        self.comboBox.setItemText(1, _translate("Dialog_Parametrs", "2", None))
        self.comboBox.setItemText(2, _translate("Dialog_Parametrs", "3", None))
        self.comboBox.setItemText(3, _translate("Dialog_Parametrs", "4", None))
        self.comboBox.setItemText(4, _translate("Dialog_Parametrs", "5", None))
        self.comboBox.setItemText(5, _translate("Dialog_Parametrs", "6", None))
        self.comboBox.setItemText(6, _translate("Dialog_Parametrs", "7", None))
        self.comboBox.setItemText(7, _translate("Dialog_Parametrs", "8", None))
        self.comboBox.setItemText(8, _translate("Dialog_Parametrs", "9", None))
        self.comboBox.setItemText(9, _translate("Dialog_Parametrs", "10", None))
        self.comboBox.setItemText(10, _translate("Dialog_Parametrs", "11", None))
        self.comboBox.setItemText(11, _translate("Dialog_Parametrs", "12", None))
        self.comboBox.setItemText(12, _translate("Dialog_Parametrs", "13", None))
        self.comboBox.setItemText(13, _translate("Dialog_Parametrs", "14", None))
        self.comboBox.setItemText(14, _translate("Dialog_Parametrs", "15", None))
        self.comboBox.setItemText(15, _translate("Dialog_Parametrs", "16", None))
        self.comboBox.setItemText(16, _translate("Dialog_Parametrs", "17", None))
        self.comboBox.setItemText(17, _translate("Dialog_Parametrs", "18", None))
        self.comboBox.setItemText(18, _translate("Dialog_Parametrs", "19", None))
        self.comboBox.setItemText(19, _translate("Dialog_Parametrs", "20", None))
        self.comboBox.setItemText(20, _translate("Dialog_Parametrs", "21", None))
        self.comboBox.setItemText(21, _translate("Dialog_Parametrs", "22", None))
        self.comboBox.setItemText(22, _translate("Dialog_Parametrs", "23", None))
        self.comboBox.setItemText(23, _translate("Dialog_Parametrs", "24", None))
        self.comboBox.setItemText(24, _translate("Dialog_Parametrs", "25", None))
        self.comboBox.setItemText(25, _translate("Dialog_Parametrs", "26", None))
        self.comboBox.setItemText(26, _translate("Dialog_Parametrs", "27", None))
        self.comboBox.setItemText(27, _translate("Dialog_Parametrs", "28", None))
        self.comboBox.setItemText(28, _translate("Dialog_Parametrs", "29", None))
        self.comboBox.setItemText(29, _translate("Dialog_Parametrs", "30", None))
        self.label_48.setText(_translate("Dialog_Parametrs", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Parameter 1</span></p></body></html>", None))
        self.label_41.setText(_translate("Dialog_Parametrs", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Parameter 2</span></p></body></html>", None))
        self.label_5.setText(_translate("Dialog_Parametrs", "Element Name", None))
        self.label_7.setText(_translate("Dialog_Parametrs", "Units", None))
        self.label_8.setText(_translate("Dialog_Parametrs", "Min. Value", None))
        self.label_9.setText(_translate("Dialog_Parametrs", "Max Value", None))
        self.label_10.setText(_translate("Dialog_Parametrs", "No. of Characters", None))
        self.comboBox_2.setItemText(0, _translate("Dialog_Parametrs", "1", None))
        self.comboBox_2.setItemText(1, _translate("Dialog_Parametrs", "2", None))
        self.comboBox_2.setItemText(2, _translate("Dialog_Parametrs", "3", None))
        self.comboBox_2.setItemText(3, _translate("Dialog_Parametrs", "4", None))
        self.comboBox_2.setItemText(4, _translate("Dialog_Parametrs", "5", None))
        self.comboBox_2.setItemText(5, _translate("Dialog_Parametrs", "6", None))
        self.comboBox_2.setItemText(6, _translate("Dialog_Parametrs", "7", None))
        self.comboBox_2.setItemText(7, _translate("Dialog_Parametrs", "8", None))
        self.comboBox_2.setItemText(8, _translate("Dialog_Parametrs", "9", None))
        self.comboBox_2.setItemText(9, _translate("Dialog_Parametrs", "10", None))
        self.comboBox_2.setItemText(10, _translate("Dialog_Parametrs", "11", None))
        self.comboBox_2.setItemText(11, _translate("Dialog_Parametrs", "12", None))
        self.comboBox_2.setItemText(12, _translate("Dialog_Parametrs", "13", None))
        self.comboBox_2.setItemText(13, _translate("Dialog_Parametrs", "14", None))
        self.comboBox_2.setItemText(14, _translate("Dialog_Parametrs", "15", None))
        self.comboBox_2.setItemText(15, _translate("Dialog_Parametrs", "16", None))
        self.comboBox_2.setItemText(16, _translate("Dialog_Parametrs", "17", None))
        self.comboBox_2.setItemText(17, _translate("Dialog_Parametrs", "18", None))
        self.comboBox_2.setItemText(18, _translate("Dialog_Parametrs", "19", None))
        self.comboBox_2.setItemText(19, _translate("Dialog_Parametrs", "20", None))
        self.comboBox_2.setItemText(20, _translate("Dialog_Parametrs", "21", None))
        self.comboBox_2.setItemText(21, _translate("Dialog_Parametrs", "22", None))
        self.comboBox_2.setItemText(22, _translate("Dialog_Parametrs", "23", None))
        self.comboBox_2.setItemText(23, _translate("Dialog_Parametrs", "24", None))
        self.comboBox_2.setItemText(24, _translate("Dialog_Parametrs", "25", None))
        self.comboBox_2.setItemText(25, _translate("Dialog_Parametrs", "26", None))
        self.comboBox_2.setItemText(26, _translate("Dialog_Parametrs", "27", None))
        self.comboBox_2.setItemText(27, _translate("Dialog_Parametrs", "28", None))
        self.comboBox_2.setItemText(28, _translate("Dialog_Parametrs", "29", None))
        self.comboBox_2.setItemText(29, _translate("Dialog_Parametrs", "30", None))
        self.label_21.setText(_translate("Dialog_Parametrs", "Element Name", None))
        self.label_22.setText(_translate("Dialog_Parametrs", "Units", None))
        self.label_23.setText(_translate("Dialog_Parametrs", "Min. Value", None))
        self.label_24.setText(_translate("Dialog_Parametrs", "Max Value", None))
        self.label_25.setText(_translate("Dialog_Parametrs", "No. of Characters", None))
        self.comboBox_5.setItemText(0, _translate("Dialog_Parametrs", "1", None))
        self.comboBox_5.setItemText(1, _translate("Dialog_Parametrs", "2", None))
        self.comboBox_5.setItemText(2, _translate("Dialog_Parametrs", "3", None))
        self.comboBox_5.setItemText(3, _translate("Dialog_Parametrs", "4", None))
        self.comboBox_5.setItemText(4, _translate("Dialog_Parametrs", "5", None))
        self.comboBox_5.setItemText(5, _translate("Dialog_Parametrs", "6", None))
        self.comboBox_5.setItemText(6, _translate("Dialog_Parametrs", "7", None))
        self.comboBox_5.setItemText(7, _translate("Dialog_Parametrs", "8", None))
        self.comboBox_5.setItemText(8, _translate("Dialog_Parametrs", "9", None))
        self.comboBox_5.setItemText(9, _translate("Dialog_Parametrs", "10", None))
        self.comboBox_5.setItemText(10, _translate("Dialog_Parametrs", "11", None))
        self.comboBox_5.setItemText(11, _translate("Dialog_Parametrs", "12", None))
        self.comboBox_5.setItemText(12, _translate("Dialog_Parametrs", "13", None))
        self.comboBox_5.setItemText(13, _translate("Dialog_Parametrs", "14", None))
        self.comboBox_5.setItemText(14, _translate("Dialog_Parametrs", "15", None))
        self.comboBox_5.setItemText(15, _translate("Dialog_Parametrs", "16", None))
        self.comboBox_5.setItemText(16, _translate("Dialog_Parametrs", "17", None))
        self.comboBox_5.setItemText(17, _translate("Dialog_Parametrs", "18", None))
        self.comboBox_5.setItemText(18, _translate("Dialog_Parametrs", "19", None))
        self.comboBox_5.setItemText(19, _translate("Dialog_Parametrs", "20", None))
        self.comboBox_5.setItemText(20, _translate("Dialog_Parametrs", "21", None))
        self.comboBox_5.setItemText(21, _translate("Dialog_Parametrs", "22", None))
        self.comboBox_5.setItemText(22, _translate("Dialog_Parametrs", "23", None))
        self.comboBox_5.setItemText(23, _translate("Dialog_Parametrs", "24", None))
        self.comboBox_5.setItemText(24, _translate("Dialog_Parametrs", "25", None))
        self.comboBox_5.setItemText(25, _translate("Dialog_Parametrs", "26", None))
        self.comboBox_5.setItemText(26, _translate("Dialog_Parametrs", "27", None))
        self.comboBox_5.setItemText(27, _translate("Dialog_Parametrs", "28", None))
        self.comboBox_5.setItemText(28, _translate("Dialog_Parametrs", "29", None))
        self.comboBox_5.setItemText(29, _translate("Dialog_Parametrs", "30", None))
        self.label_42.setText(_translate("Dialog_Parametrs", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Parameter 3</span></p></body></html>", None))
        self.label_26.setText(_translate("Dialog_Parametrs", "Element Name", None))
        self.label_27.setText(_translate("Dialog_Parametrs", "Units", None))
        self.label_28.setText(_translate("Dialog_Parametrs", "Min. Value", None))
        self.label_29.setText(_translate("Dialog_Parametrs", "Max Value", None))
        self.label_30.setText(_translate("Dialog_Parametrs", "No. of Characters", None))
        self.comboBox_6.setItemText(0, _translate("Dialog_Parametrs", "1", None))
        self.comboBox_6.setItemText(1, _translate("Dialog_Parametrs", "2", None))
        self.comboBox_6.setItemText(2, _translate("Dialog_Parametrs", "3", None))
        self.comboBox_6.setItemText(3, _translate("Dialog_Parametrs", "4", None))
        self.comboBox_6.setItemText(4, _translate("Dialog_Parametrs", "5", None))
        self.comboBox_6.setItemText(5, _translate("Dialog_Parametrs", "6", None))
        self.comboBox_6.setItemText(6, _translate("Dialog_Parametrs", "7", None))
        self.comboBox_6.setItemText(7, _translate("Dialog_Parametrs", "8", None))
        self.comboBox_6.setItemText(8, _translate("Dialog_Parametrs", "9", None))
        self.comboBox_6.setItemText(9, _translate("Dialog_Parametrs", "10", None))
        self.comboBox_6.setItemText(10, _translate("Dialog_Parametrs", "11", None))
        self.comboBox_6.setItemText(11, _translate("Dialog_Parametrs", "12", None))
        self.comboBox_6.setItemText(12, _translate("Dialog_Parametrs", "13", None))
        self.comboBox_6.setItemText(13, _translate("Dialog_Parametrs", "14", None))
        self.comboBox_6.setItemText(14, _translate("Dialog_Parametrs", "15", None))
        self.comboBox_6.setItemText(15, _translate("Dialog_Parametrs", "16", None))
        self.comboBox_6.setItemText(16, _translate("Dialog_Parametrs", "17", None))
        self.comboBox_6.setItemText(17, _translate("Dialog_Parametrs", "18", None))
        self.comboBox_6.setItemText(18, _translate("Dialog_Parametrs", "19", None))
        self.comboBox_6.setItemText(19, _translate("Dialog_Parametrs", "20", None))
        self.comboBox_6.setItemText(20, _translate("Dialog_Parametrs", "21", None))
        self.comboBox_6.setItemText(21, _translate("Dialog_Parametrs", "22", None))
        self.comboBox_6.setItemText(22, _translate("Dialog_Parametrs", "23", None))
        self.comboBox_6.setItemText(23, _translate("Dialog_Parametrs", "24", None))
        self.comboBox_6.setItemText(24, _translate("Dialog_Parametrs", "25", None))
        self.comboBox_6.setItemText(25, _translate("Dialog_Parametrs", "26", None))
        self.comboBox_6.setItemText(26, _translate("Dialog_Parametrs", "27", None))
        self.comboBox_6.setItemText(27, _translate("Dialog_Parametrs", "28", None))
        self.comboBox_6.setItemText(28, _translate("Dialog_Parametrs", "29", None))
        self.comboBox_6.setItemText(29, _translate("Dialog_Parametrs", "30", None))
        self.label_43.setText(_translate("Dialog_Parametrs", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Parameter 4</span></p></body></html>", None))
        self.label_31.setText(_translate("Dialog_Parametrs", "Element Name", None))
        self.label_32.setText(_translate("Dialog_Parametrs", "Units", None))
        self.label_33.setText(_translate("Dialog_Parametrs", "Min. Value", None))
        self.label_34.setText(_translate("Dialog_Parametrs", "Max Value", None))
        self.label_35.setText(_translate("Dialog_Parametrs", "No. of Characters", None))
        self.comboBox_7.setItemText(0, _translate("Dialog_Parametrs", "1", None))
        self.comboBox_7.setItemText(1, _translate("Dialog_Parametrs", "2", None))
        self.comboBox_7.setItemText(2, _translate("Dialog_Parametrs", "3", None))
        self.comboBox_7.setItemText(3, _translate("Dialog_Parametrs", "4", None))
        self.comboBox_7.setItemText(4, _translate("Dialog_Parametrs", "5", None))
        self.comboBox_7.setItemText(5, _translate("Dialog_Parametrs", "6", None))
        self.comboBox_7.setItemText(6, _translate("Dialog_Parametrs", "7", None))
        self.comboBox_7.setItemText(7, _translate("Dialog_Parametrs", "8", None))
        self.comboBox_7.setItemText(8, _translate("Dialog_Parametrs", "9", None))
        self.comboBox_7.setItemText(9, _translate("Dialog_Parametrs", "10", None))
        self.comboBox_7.setItemText(10, _translate("Dialog_Parametrs", "11", None))
        self.comboBox_7.setItemText(11, _translate("Dialog_Parametrs", "12", None))
        self.comboBox_7.setItemText(12, _translate("Dialog_Parametrs", "13", None))
        self.comboBox_7.setItemText(13, _translate("Dialog_Parametrs", "14", None))
        self.comboBox_7.setItemText(14, _translate("Dialog_Parametrs", "15", None))
        self.comboBox_7.setItemText(15, _translate("Dialog_Parametrs", "16", None))
        self.comboBox_7.setItemText(16, _translate("Dialog_Parametrs", "17", None))
        self.comboBox_7.setItemText(17, _translate("Dialog_Parametrs", "18", None))
        self.comboBox_7.setItemText(18, _translate("Dialog_Parametrs", "19", None))
        self.comboBox_7.setItemText(19, _translate("Dialog_Parametrs", "20", None))
        self.comboBox_7.setItemText(20, _translate("Dialog_Parametrs", "21", None))
        self.comboBox_7.setItemText(21, _translate("Dialog_Parametrs", "22", None))
        self.comboBox_7.setItemText(22, _translate("Dialog_Parametrs", "23", None))
        self.comboBox_7.setItemText(23, _translate("Dialog_Parametrs", "24", None))
        self.comboBox_7.setItemText(24, _translate("Dialog_Parametrs", "25", None))
        self.comboBox_7.setItemText(25, _translate("Dialog_Parametrs", "26", None))
        self.comboBox_7.setItemText(26, _translate("Dialog_Parametrs", "27", None))
        self.comboBox_7.setItemText(27, _translate("Dialog_Parametrs", "28", None))
        self.comboBox_7.setItemText(28, _translate("Dialog_Parametrs", "29", None))
        self.comboBox_7.setItemText(29, _translate("Dialog_Parametrs", "30", None))
        self.label_44.setText(_translate("Dialog_Parametrs", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Parameter 5</span></p></body></html>", None))
        self.label_11.setText(_translate("Dialog_Parametrs", "Element Name", None))
        self.label_12.setText(_translate("Dialog_Parametrs", "Units", None))
        self.label_13.setText(_translate("Dialog_Parametrs", "Min. Value", None))
        self.label_14.setText(_translate("Dialog_Parametrs", "Max Value", None))
        self.label_15.setText(_translate("Dialog_Parametrs", "No. of Characters", None))
        self.comboBox_3.setItemText(0, _translate("Dialog_Parametrs", "1", None))
        self.comboBox_3.setItemText(1, _translate("Dialog_Parametrs", "2", None))
        self.comboBox_3.setItemText(2, _translate("Dialog_Parametrs", "3", None))
        self.comboBox_3.setItemText(3, _translate("Dialog_Parametrs", "4", None))
        self.comboBox_3.setItemText(4, _translate("Dialog_Parametrs", "5", None))
        self.comboBox_3.setItemText(5, _translate("Dialog_Parametrs", "6", None))
        self.comboBox_3.setItemText(6, _translate("Dialog_Parametrs", "7", None))
        self.comboBox_3.setItemText(7, _translate("Dialog_Parametrs", "8", None))
        self.comboBox_3.setItemText(8, _translate("Dialog_Parametrs", "9", None))
        self.comboBox_3.setItemText(9, _translate("Dialog_Parametrs", "10", None))
        self.comboBox_3.setItemText(10, _translate("Dialog_Parametrs", "11", None))
        self.comboBox_3.setItemText(11, _translate("Dialog_Parametrs", "12", None))
        self.comboBox_3.setItemText(12, _translate("Dialog_Parametrs", "13", None))
        self.comboBox_3.setItemText(13, _translate("Dialog_Parametrs", "14", None))
        self.comboBox_3.setItemText(14, _translate("Dialog_Parametrs", "15", None))
        self.comboBox_3.setItemText(15, _translate("Dialog_Parametrs", "16", None))
        self.comboBox_3.setItemText(16, _translate("Dialog_Parametrs", "17", None))
        self.comboBox_3.setItemText(17, _translate("Dialog_Parametrs", "18", None))
        self.comboBox_3.setItemText(18, _translate("Dialog_Parametrs", "19", None))
        self.comboBox_3.setItemText(19, _translate("Dialog_Parametrs", "20", None))
        self.comboBox_3.setItemText(20, _translate("Dialog_Parametrs", "21", None))
        self.comboBox_3.setItemText(21, _translate("Dialog_Parametrs", "22", None))
        self.comboBox_3.setItemText(22, _translate("Dialog_Parametrs", "23", None))
        self.comboBox_3.setItemText(23, _translate("Dialog_Parametrs", "24", None))
        self.comboBox_3.setItemText(24, _translate("Dialog_Parametrs", "25", None))
        self.comboBox_3.setItemText(25, _translate("Dialog_Parametrs", "26", None))
        self.comboBox_3.setItemText(26, _translate("Dialog_Parametrs", "27", None))
        self.comboBox_3.setItemText(27, _translate("Dialog_Parametrs", "28", None))
        self.comboBox_3.setItemText(28, _translate("Dialog_Parametrs", "29", None))
        self.comboBox_3.setItemText(29, _translate("Dialog_Parametrs", "30", None))
        self.label_45.setText(_translate("Dialog_Parametrs", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Parameter 6</span></p></body></html>", None))
        self.label_16.setText(_translate("Dialog_Parametrs", "Element Name", None))
        self.label_17.setText(_translate("Dialog_Parametrs", "Units", None))
        self.label_18.setText(_translate("Dialog_Parametrs", "Min. Value", None))
        self.label_19.setText(_translate("Dialog_Parametrs", "Max Value", None))
        self.label_20.setText(_translate("Dialog_Parametrs", "No. of Characters", None))
        self.comboBox_4.setItemText(0, _translate("Dialog_Parametrs", "1", None))
        self.comboBox_4.setItemText(1, _translate("Dialog_Parametrs", "2", None))
        self.comboBox_4.setItemText(2, _translate("Dialog_Parametrs", "3", None))
        self.comboBox_4.setItemText(3, _translate("Dialog_Parametrs", "4", None))
        self.comboBox_4.setItemText(4, _translate("Dialog_Parametrs", "5", None))
        self.comboBox_4.setItemText(5, _translate("Dialog_Parametrs", "6", None))
        self.comboBox_4.setItemText(6, _translate("Dialog_Parametrs", "7", None))
        self.comboBox_4.setItemText(7, _translate("Dialog_Parametrs", "8", None))
        self.comboBox_4.setItemText(8, _translate("Dialog_Parametrs", "9", None))
        self.comboBox_4.setItemText(9, _translate("Dialog_Parametrs", "10", None))
        self.comboBox_4.setItemText(10, _translate("Dialog_Parametrs", "11", None))
        self.comboBox_4.setItemText(11, _translate("Dialog_Parametrs", "12", None))
        self.comboBox_4.setItemText(12, _translate("Dialog_Parametrs", "13", None))
        self.comboBox_4.setItemText(13, _translate("Dialog_Parametrs", "14", None))
        self.comboBox_4.setItemText(14, _translate("Dialog_Parametrs", "15", None))
        self.comboBox_4.setItemText(15, _translate("Dialog_Parametrs", "16", None))
        self.comboBox_4.setItemText(16, _translate("Dialog_Parametrs", "17", None))
        self.comboBox_4.setItemText(17, _translate("Dialog_Parametrs", "18", None))
        self.comboBox_4.setItemText(18, _translate("Dialog_Parametrs", "19", None))
        self.comboBox_4.setItemText(19, _translate("Dialog_Parametrs", "20", None))
        self.comboBox_4.setItemText(20, _translate("Dialog_Parametrs", "21", None))
        self.comboBox_4.setItemText(21, _translate("Dialog_Parametrs", "22", None))
        self.comboBox_4.setItemText(22, _translate("Dialog_Parametrs", "23", None))
        self.comboBox_4.setItemText(23, _translate("Dialog_Parametrs", "24", None))
        self.comboBox_4.setItemText(24, _translate("Dialog_Parametrs", "25", None))
        self.comboBox_4.setItemText(25, _translate("Dialog_Parametrs", "26", None))
        self.comboBox_4.setItemText(26, _translate("Dialog_Parametrs", "27", None))
        self.comboBox_4.setItemText(27, _translate("Dialog_Parametrs", "28", None))
        self.comboBox_4.setItemText(28, _translate("Dialog_Parametrs", "29", None))
        self.comboBox_4.setItemText(29, _translate("Dialog_Parametrs", "30", None))
        self.label_46.setText(_translate("Dialog_Parametrs", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Parameter 7</span></p></body></html>", None))
        self.label_47.setText(_translate("Dialog_Parametrs", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Parameter 8</span></p></body></html>", None))
        self.label_36.setText(_translate("Dialog_Parametrs", "Element Name", None))
        self.label_37.setText(_translate("Dialog_Parametrs", "Units", None))
        self.label_38.setText(_translate("Dialog_Parametrs", "Min. Value", None))
        self.label_39.setText(_translate("Dialog_Parametrs", "Max Value", None))
        self.label_40.setText(_translate("Dialog_Parametrs", "No. of Characters", None))
        self.comboBox_8.setItemText(0, _translate("Dialog_Parametrs", "1", None))
        self.comboBox_8.setItemText(1, _translate("Dialog_Parametrs", "2", None))
        self.comboBox_8.setItemText(2, _translate("Dialog_Parametrs", "3", None))
        self.comboBox_8.setItemText(3, _translate("Dialog_Parametrs", "4", None))
        self.comboBox_8.setItemText(4, _translate("Dialog_Parametrs", "5", None))
        self.comboBox_8.setItemText(5, _translate("Dialog_Parametrs", "6", None))
        self.comboBox_8.setItemText(6, _translate("Dialog_Parametrs", "7", None))
        self.comboBox_8.setItemText(7, _translate("Dialog_Parametrs", "8", None))
        self.comboBox_8.setItemText(8, _translate("Dialog_Parametrs", "9", None))
        self.comboBox_8.setItemText(9, _translate("Dialog_Parametrs", "10", None))
        self.comboBox_8.setItemText(10, _translate("Dialog_Parametrs", "11", None))
        self.comboBox_8.setItemText(11, _translate("Dialog_Parametrs", "12", None))
        self.comboBox_8.setItemText(12, _translate("Dialog_Parametrs", "13", None))
        self.comboBox_8.setItemText(13, _translate("Dialog_Parametrs", "14", None))
        self.comboBox_8.setItemText(14, _translate("Dialog_Parametrs", "15", None))
        self.comboBox_8.setItemText(15, _translate("Dialog_Parametrs", "16", None))
        self.comboBox_8.setItemText(16, _translate("Dialog_Parametrs", "17", None))
        self.comboBox_8.setItemText(17, _translate("Dialog_Parametrs", "18", None))
        self.comboBox_8.setItemText(18, _translate("Dialog_Parametrs", "19", None))
        self.comboBox_8.setItemText(19, _translate("Dialog_Parametrs", "20", None))
        self.comboBox_8.setItemText(20, _translate("Dialog_Parametrs", "21", None))
        self.comboBox_8.setItemText(21, _translate("Dialog_Parametrs", "22", None))
        self.comboBox_8.setItemText(22, _translate("Dialog_Parametrs", "23", None))
        self.comboBox_8.setItemText(23, _translate("Dialog_Parametrs", "24", None))
        self.comboBox_8.setItemText(24, _translate("Dialog_Parametrs", "25", None))
        self.comboBox_8.setItemText(25, _translate("Dialog_Parametrs", "26", None))
        self.comboBox_8.setItemText(26, _translate("Dialog_Parametrs", "27", None))
        self.comboBox_8.setItemText(27, _translate("Dialog_Parametrs", "28", None))
        self.comboBox_8.setItemText(28, _translate("Dialog_Parametrs", "29", None))
        self.comboBox_8.setItemText(29, _translate("Dialog_Parametrs", "30", None))

